hadoop:
  namenodes:
    - nameservices: logs-hdfs
      namenodesAddr: [ "host1", "host2" ]
      namenodes: ["namenode1", "namenode2"]
      # Optional
      user: hdfs
      # Optional
      password:
      port: 8020
      matchPathKeys: [ "flume" ]
      # kerberos
      enableKerberos: false
      # /etc/krb5.conf
      krb5Conf: ""
      # hdfs/*@EXAMPLE.COM
      principalPattern:  ""
      # admin
      loginUser: "admin"
      # /var/kerberos/krb5kdc/admin.keytab
      keytabPath: "/opt/compassCompile/keberosconf/admin.keytab"
      coresite : "/opt/compassCompile/keberosconf/hadoop-conf/core-site.xml"
      hdfssite : "/opt/compassCompile/keberosconf/hadoop-conf/hdfs-site.xml"
