spring:
  datasource:
    url: jdbc:mysql://localhost:33066/compass?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
  kafka:
    bootstrap-servers: "localhost:9095"
    taskinstancetopics: "task_instance"
    consumer:
      taskappgroupid: "task_instance_group02"
      auto-offset-reset: "earliest"
      max-poll-interval-ms: 300000
      security-protocol: ""
      sasl-mechanism: ""
      sasl-jaas-config: ""
  redis:
    host: localhost
    port: 6379
    password: "root"
    database: 0
  hdfs:
    base-path: ""

custom:
  delayedTask:
    enable: true
    queue: "{lua}:task:application"
    processing: "{lua}:task-processing"
    delayedSeconds: 5
    tryTimes: 20
  # 从上到下串行执行解析到任务的applicationId
  rules:
    - logPathDep: # 日志依赖查询
        query: ""    # 变量依赖查询
      logPathJoins: # 拼接日志绝对路径
        hdfsbasepath: "" # 相当于根目录，常量
      extractLog: # 根据组装的日志路径解析日志
        regex: "^.*Submitted application (?<applicationId>application_[0-9]+_[0-9]+).*$"     # 匹配规则
        name: "applicationId"      # 匹配文本名，最后必须有applicationId
