hadoop:
  namenodes:
    - nameservices: nameservice1
      namenodesAddr: [ "qdedhtest0", "qdedhtest1" ]
      namenodes: [ "namenode30", "namenode172" ]
      user: hdfs
      password:
      port: 8020
      # scheduler platform hdfs log path keyword identification, used by task-application
      matchPathKeys: [ "flume" ]

  yarn:
    - clusterName: "bigdata"
      resourceManager: [ "qdedhtest2:8088","qdedhtest1:8088" ]
      jobHistoryServer: "qdedhtest0:19888"

  spark:
    sparkHistoryServer: [ "qdedhtest1:18088" ]
