hadoop:
  namenodes:
    - nameservices: nameservice1
      namenodesAddr: [ "qdedhtest0", "qdedhtest1" ]
      namenodes: [ "namenode30", "namenode172" ]
      user: hdfs
      password:
      port: 8020
      # scheduler platform hdfs log path keyword identification, used by task-application
      matchPathKeys: [ "flume" ]
      # kerberos
      enableKerberos: true
      # /etc/krb5.conf
      krb5Conf: "/opt/compassCompile/keberosconf/krb5.conf"
      # hdfs/*@EXAMPLE.COM
      principalPattern:  "hdfs/*@HAIER.COM"
      # admin
      loginUser: "admin"
      # /var/kerberos/krb5kdc/admin.keytab
      keytabPath: "/opt/compassCompile/keberosconf/admin.keytab"
      # core-site.xml
      coresite: "/opt/compassCompile/keberosconf/hadoop-conf/core-site.xml"
      # hdfs-site.xml
      hdfssite: "/opt/compassCompile/keberosconf/hadoop-conf/hdfs-site.xml"

  yarn:
    - clusterName: "bigdata"
      resourceManager: [ "qdedhtest2:8088","qdedhtest1:8088" ]
      jobHistoryServer: "qdedhtest0:19888"

  spark:
    sparkHistoryServer: [ "qdedhtest1:18088" ]
