server:
  port: 7072

spring:
  profiles:
    active: hadoop
  task:
    scheduling:
      pool:
        size: 10
  redis:
    host: localhost
    port: 6379
    password: "root"
    database: 0

  elasticsearch:
    nodes: localhost:19527
    username:
    password:
    yarn-app-prefix: "compass-yarn-app-"
    spark-app-prefix: "compass-spark-app-"

scheduler:
  clusterMeta:
    enable: true
    cron: "0 */30 * * * ?"
  yarnMeta:
    enable: true
    cron: "0/30 * * * * ?"
    # hour
    startedTimeBegin: 6
  sparkMeta:
    enable: true
    cron: "0/30 * * * * ?"
    limitCount: 1000
